[brothers]

fire_cooldown = 0.5
fireball_speed = 200
scale = 1.2
speed = 100

[enemies]

texture = "enemies"

[enemies.goomba]
scale = 1.2

[items]

texture = "items"

[items.coin]
scale = 0.8

[items.mushroom]
scale = 1.2

[items.flower]
scale = 1.2

[features]

texture = "tileset"

[features.pipe]
scale = 1.0