[brothers]

scale = 1.2

[brothers.mario]

[brothers.luigi]

[enemies]

texture = "enemies"

[enemies.goomba]
scale = 1.2

[items]

texture = "items"

[items.coin]
scale = 0.8

[items.mushroom]
scale = 1.2

[items.flower]
scale = 1.2