[brothers]

texture = "brothers"

[brothers.mario]
texture_rect = [43, 9, 16, 16]
scale = 1.2

[brothers.luigi]
texture_rect = [43, 74, 16, 16]
scale = 1.2

[enemies]

texture = "enemies"

[enemies.goomba]
texture_rect = [1, 28, 16, 16]
scale = 1.2

[items]

texture = "items"

[items.coin]
scale = 0.8

[items.mushroom]
texture_rect = [0, 0, 16, 16]
scale = 1.2

[items.flower]
scale = 1.2