[brothers]

scale = 1.2
speed = 100

[brothers.fireball]
cooldown = 0.5
speed = 200

[enemies]

[enemies.goomba]
scale = 1.2
speed = 100

[items]

[items.coin]
scale = 0.8

[items.mushroom]
scale = 1.2

[items.flower]
scale = 1.2

[features]

[features.pipe]
scale = 1.0