name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, MinSizeRel]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Boost
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install boost
      - name: Install Ubuntu packages
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt-get install -y libudev-dev libgl-dev
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.9
      - name: Install Conan
        uses: turtlebrowser/get-conan@main
      - name: Check out repository
        uses: actions/checkout@v2
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
      - uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-count
      - name: Build
        run: cmake --build . --config ${{ matrix.configuration }} --parallel ${{ steps.cpu-count.outputs.count }}
