on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, MinSizeRel]
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.9
      - name: Install Conan
        uses: turtlebrowser/get-conan@main
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
      - uses: SimenB/github-actions-cpu-cores@v1
      - name: Build
        run: cmake --build . --parallel ${{ steps.cpu-cores.outputs.count }}
